### ISSUE TITLE
Transfer wiki info into website

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity-im.github.io#23]
Move stuff from https://github.com/profanity-im/profanity/wiki/ to the website.

**Comment by kaffeekanne** [comment]
Since the website still uses jQuery from 5 years ago, maybe an overhaul of the website could be worth thinking about. I like static generators like hugo, so writing content becomes easier, but initially a template should be created/edited to resemble profanity.

Or ditch the webseite and rely on README.md and wiki provided by github to save resources.

**Comment by jubalh** [comment]
> Since the website still uses jQuery from 5 years ago, maybe an overhaul of the website could be worth thinking about.

The thinking about it is not the hard part :)
I thought about switching to `hugo` since I started contributing to the website. But don't want to invest the time. So for me the website is fine if we keep on updating it. It's not that many pages and it works well. So actually there is not much need for a static generator yet.

However if you want to update the jQuery dependency, feel free to submit a PR.
